### ISSUE TITLE
Add Tiny test datasets

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/pipelines#7]
The nextflow pipelines need small data sets that take less than 5 minutes to run.

**Comment by Juke34** [comment]
potential dataset from nf-core
preprocessing pipeline: https://github.com/nf-core/test-datasets/blob/rnaseq/reference/genome.fa

assembly pipeline: https://github.com/nf-core/test-datasets/tree/rnaseq/testdata + https://github.com/nf-core/test-datasets/blob/rnaseq/reference/genome.fa

AbinitioTraining; probably https://github.com/nf-core/test-datasets/blob/rnaseq/reference/genes.gff + https://github.com/nf-core/test-datasets/blob/rnaseq/reference/genome.fa

**Comment by Juke34** [comment]
Moved to https://github.com/NBISweden/pipelines-nextflow/
